// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRfQih5eXNYjE6BTJeMwEgMgDYlULZ0D8',
    appId: '1:342207930624:web:0329842d877ec5bf9553e5',
    messagingSenderId: '342207930624',
    projectId: 'stay-mitra-20604',
    authDomain: 'stay-mitra-20604.firebaseapp.com',
    storageBucket: 'stay-mitra-20604.firebasestorage.app',
    measurementId: 'G-4GVHFRN68S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF-auHY3xoOrTbu3-YAP513cFCOhLqdmM',
    appId: '1:342207930624:android:93173760ca87ff909553e5',
    messagingSenderId: '342207930624',
    projectId: 'stay-mitra-20604',
    storageBucket: 'stay-mitra-20604.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkti5rI5bzDCAgzght6L3cOwUG-r_xhvs',
    appId: '1:342207930624:ios:78b31c96f6f4132b9553e5',
    messagingSenderId: '342207930624',
    projectId: 'stay-mitra-20604',
    storageBucket: 'stay-mitra-20604.firebasestorage.app',
    iosBundleId: 'com.example.stayMitra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkti5rI5bzDCAgzght6L3cOwUG-r_xhvs',
    appId: '1:342207930624:ios:78b31c96f6f4132b9553e5',
    messagingSenderId: '342207930624',
    projectId: 'stay-mitra-20604',
    storageBucket: 'stay-mitra-20604.firebasestorage.app',
    iosBundleId: 'com.example.stayMitra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRfQih5eXNYjE6BTJeMwEgMgDYlULZ0D8',
    appId: '1:342207930624:web:518a3fb9d8bf66ba9553e5',
    messagingSenderId: '342207930624',
    projectId: 'stay-mitra-20604',
    authDomain: 'stay-mitra-20604.firebaseapp.com',
    storageBucket: 'stay-mitra-20604.firebasestorage.app',
    measurementId: 'G-812FVW7MG4',
  );
}
