import 'dart:async';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/foundation.dart';

class LanguageService extends ChangeNotifier {
  LanguageService._privateConstructor();

  static final LanguageService instance =
      LanguageService._privateConstructor();

  String _language = 'English';

  String get language => _language;

  static const List<String> supportedLanguages = [
    'English', 'Telugu', 'Kannada', 'Hindi', 'Tamil', 'Malayalam',
    'Marathi', 'Bengali', 'Gujarati', 'Punjabi', 'Odia', 'Assamese', 'Urdu',
  ];

  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;
  bool _initialized = false;
  bool _initializing = false;
  String? _loadedUserId;

  Future<void> initialize() async {
    final user = _auth.currentUser;
    if (_initializing) return;
    if (_initialized && _loadedUserId == user?.uid) return;
    if (user == null) {
      // Authentication may complete later (for example after Splash/Login).
      // Keep the service uninitialized so Dashboard can load the saved
      // language after FirebaseAuth.currentUser becomes available.
      return;
    }
    _initializing = true;
    try {
      final snapshot = await _firestore
          .collection('owners').doc(user.uid)
          .collection('settings').doc('app').get();
      final savedLanguage = snapshot.data()?['language'];
      if (savedLanguage is String && supportedLanguages.contains(savedLanguage)) {
        _language = savedLanguage;
      } else {
        _language = 'English';
      }
    } catch (e) {
      debugPrint('LanguageService initialize error: $e');
    } finally {
      _initializing = false;
      _initialized = true;
      _loadedUserId = user.uid;
      notifyListeners();
    }
  }

  void setLanguage(String language) {
    if (!supportedLanguages.contains(language)) return;
    if (_language == language) return;
    _language = language;
    notifyListeners();
    unawaited(_saveLanguageToFirebase(language));
  }

  Future<void> _saveLanguageToFirebase(String language) async {
    final user = _auth.currentUser;
    if (user == null) return;
    try {
      await _firestore
          .collection('owners').doc(user.uid)
          .collection('settings').doc('app')
          .set({
        'language': language,
        'updated_at': FieldValue.serverTimestamp(),
      }, SetOptions(merge: true));
    } catch (e) {
      debugPrint('LanguageService save error: $e');
    }
  }

  String get(String key) {
    return _translations[_language]?[key] ??
        _translations['English']?[key] ??
        key;
  }

  // ============================================================
  // TRANSLATIONS
  // ============================================================

  static const Map<String, Map<String, String>> _translations = {
    // ==========================================================
    // ENGLISH
    // ==========================================================

    'English': {
      'dashboard': 'Dashboard',
      'settings': 'Settings',
      'reports': 'Reports',
      'tenant_management': 'Tenant Management',
      'tenants': 'Tenants',
      'check_in': 'Check-in',
      'check_out': 'Check-out',
      'day_sheet': 'Day Sheet',
      'more': 'More',
      'save': 'Save',
      'cancel': 'Cancel',
      'search': 'Search',
      'active': 'Active',
      'vacated': 'Vacated',
      'income': 'Income',
      'expense': 'Expense',
      'add_tenant': 'Add Tenant',
      'tenant': 'Tenant',
      'rent': 'Rent',
      'monthly_rent': 'Monthly Rent',
      'phone': 'Phone',
      'room': 'Room',
      'bed': 'Bed',
      'available': 'Available',
      'occupied': 'Occupied',
      'total': 'Total',
      'name': 'Name',
      'date': 'Date',
      'status': 'Status',
      'notes': 'Notes',
      'confirm': 'Confirm',
      'delete': 'Delete',
      'edit': 'Edit',
      'update': 'Update',
      'close': 'Close',
      'back': 'Back',
      'refresh': 'Refresh',
      'language': 'Language',
      'select_language': 'Select Language',
      'welcome': 'Welcome',
      'recent_transactions': 'Recent Transactions',
      'financial_summary': 'Financial Summary',
      'occupancy_overview': 'Occupancy Overview',
      'payment_methods': 'Payment Methods',
      'transaction_summary': 'Transaction Summary',
      'check_in_details': 'Check-in Details',
      'check_out_details': 'Check-out Details',
      'recent_check_ins': 'Recent Check-ins',
      'recent_check_outs': 'Recent Check-outs',
      'confirm_check_in': 'Confirm Check-in',
      'confirm_check_out': 'Confirm Check-out',
      'no_data': 'No data available',
      'loading': 'Loading...',

      'property_overview': 'Property Overview',
      'quick_actions': 'Quick Actions',
      'total_rooms': 'Total Rooms',
      'all_rooms': 'All Rooms',
      'total_beds': 'Total Beds',
      'all_beds': 'All Beds',
      'vacant': 'Vacant',
      'today_collection': 'Today Collection',
      'payments': 'Payments',
      'pending_rent': 'Pending Rent',
      'active_tenants': 'Active Tenants',
      'this_month_income': 'This Month Income',
      'all_income': 'All Income',
      'this_month_expense': 'This Month Expense',
      'all_expense': 'All Expense',
      'add_payment': 'Add Payment',
      'add_expense': 'Add Expense',
      'create_bill': 'Create Bill',
      'check_in_out': 'Check-in/Out',
      'upload_register': 'Upload Register',
      'pg_apartment_structure': 'PG/Apartment Structure',
      'home': 'Home',
      'rooms': 'Rooms',
      'rooms_beds': 'Rooms & Beds',
      'billing': 'Billing',
      'documents': 'Documents',
      'notifications': 'Notifications',
      'logout': 'Logout',
      'current_property': 'Current property',
      'no_pg_configured': 'No PG configured',
      'setup_pg_to_get_started': 'Set up your PG to get started',
      'menu': 'Menu',
      'accounts': 'Accounts',
      'confirm_logout': 'Are you sure you want to logout?',
    },

    // ==========================================================
    // TELUGU
    // ==========================================================

    'Telugu': {
      'dashboard': 'డాష్‌బోర్డ్',
      'settings': 'సెట్టింగ్స్',
      'reports': 'నివేదికలు',
      'tenant_management': 'టెనెంట్ నిర్వహణ',
      'tenants': 'టెనెంట్లు',
      'check_in': 'చెక్-ఇన్',
      'check_out': 'చెక్-అవుట్',
      'day_sheet': 'డే షీట్',
      'more': 'మరిన్ని',
      'save': 'సేవ్',
      'cancel': 'రద్దు',
      'search': 'వెతకండి',
      'active': 'యాక్టివ్',
      'vacated': 'ఖాళీ చేసినవారు',
      'income': 'ఆదాయం',
      'expense': 'ఖర్చు',
      'add_tenant': 'టెనెంట్‌ను జోడించండి',
      'tenant': 'టెనెంట్',
      'rent': 'అద్దె',
      'monthly_rent': 'నెలవారీ అద్దె',
      'phone': 'ఫోన్',
      'room': 'గది',
      'bed': 'బెడ్',
      'available': 'అందుబాటులో ఉంది',
      'occupied': 'ఆక్యుపైడ్',
      'total': 'మొత్తం',
      'name': 'పేరు',
      'date': 'తేదీ',
      'status': 'స్థితి',
      'notes': 'గమనికలు',
      'confirm': 'నిర్ధారించండి',
      'delete': 'తొలగించండి',
      'edit': 'ఎడిట్',
      'update': 'అప్‌డేట్',
      'close': 'మూసివేయండి',
      'back': 'వెనుకకు',
      'refresh': 'రిఫ్రెష్',
      'language': 'భాష',
      'select_language': 'భాషను ఎంచుకోండి',
      'welcome': 'స్వాగతం',
      'recent_transactions': 'ఇటీవలి లావాదేవీలు',
      'financial_summary': 'ఆర్థిక సారాంశం',
      'occupancy_overview': 'ఆక్యుపెన్సీ వివరాలు',
      'payment_methods': 'చెల్లింపు పద్ధతులు',
      'transaction_summary': 'లావాదేవీల సారాంశం',
      'check_in_details': 'చెక్-ఇన్ వివరాలు',
      'check_out_details': 'చెక్-అవుట్ వివరాలు',
      'recent_check_ins': 'ఇటీవలి చెక్-ఇన్‌లు',
      'recent_check_outs': 'ఇటీవలి చెక్-అవుట్‌లు',
      'confirm_check_in': 'చెక్-ఇన్ నిర్ధారించండి',
      'confirm_check_out': 'చెక్-అవుట్ నిర్ధారించండి',
      'no_data': 'డేటా అందుబాటులో లేదు',
      'loading': 'లోడ్ అవుతోంది...',

      'property_overview': 'ప్రాపర్టీ వివరాలు',
      'quick_actions': 'త్వరిత చర్యలు',
      'total_rooms': 'మొత్తం గదులు',
      'all_rooms': 'అన్ని గదులు',
      'total_beds': 'మొత్తం బెడ్లు',
      'all_beds': 'అన్ని బెడ్లు',
      'vacant': 'ఖాళీ',
      'today_collection': 'ఈరోజు వసూళ్లు',
      'payments': 'చెల్లింపులు',
      'pending_rent': 'బకాయి అద్దె',
      'active_tenants': 'యాక్టివ్ టెనెంట్లు',
      'this_month_income': 'ఈ నెల ఆదాయం',
      'all_income': 'మొత్తం ఆదాయం',
      'this_month_expense': 'ఈ నెల ఖర్చు',
      'all_expense': 'మొత్తం ఖర్చు',
      'add_payment': 'చెల్లింపు జోడించండి',
      'add_expense': 'ఖర్చు జోడించండి',
      'create_bill': 'బిల్ రూపొందించండి',
      'check_in_out': 'చెక్-ఇన్/అవుట్',
      'upload_register': 'రిజిస్టర్ అప్\u200cలోడ్',
      'pg_apartment_structure': 'PG/అపార్ట్\u200cమెంట్ నిర్మాణం',
      'home': 'హోమ్',
      'rooms': 'గదులు',
      'rooms_beds': 'గదులు & బెడ్లు',
      'billing': 'బిల్లింగ్',
      'documents': 'డాక్యుమెంట్లు',
      'notifications': 'నోటిఫికేషన్లు',
      'logout': 'లాగ్ అవుట్',
      'current_property': 'ప్రస్తుత ప్రాపర్టీ',
      'no_pg_configured': 'PG సెటప్ కాలేదు',
      'setup_pg_to_get_started': 'ప్రారంభించడానికి మీ PGని సెటప్ చేయండి',
      'menu': 'మెను',
      'accounts': 'ఖాతాలు',
      'confirm_logout': 'మీరు ఖచ్చితంగా లాగ్ అవుట్ చేయాలనుకుంటున్నారా?',
    },

    // ==========================================================
    // KANNADA
    // ==========================================================

    'Kannada': {
      'dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'settings': 'ಸೆಟ್ಟಿಂಗ್ಸ್',
      'reports': 'ವರದಿಗಳು',
      'tenant_management': 'ಟೆನಂಟ್ ನಿರ್ವಹಣೆ',
      'tenants': 'ಟೆನಂಟ್‌ಗಳು',
      'check_in': 'ಚೆಕ್-ಇನ್',
      'check_out': 'ಚೆಕ್-ಔಟ್',
      'day_sheet': 'ಡೇ ಶೀಟ್',
      'more': 'ಇನ್ನಷ್ಟು',
      'save': 'ಉಳಿಸಿ',
      'cancel': 'ರದ್ದುಮಾಡಿ',
      'search': 'ಹುಡುಕಿ',
      'active': 'ಸಕ್ರಿಯ',
      'vacated': 'ಖಾಲಿ ಮಾಡಿದವರು',
      'income': 'ಆದಾಯ',
      'expense': 'ಖರ್ಚು',
      'add_tenant': 'ಟೆನಂಟ್ ಸೇರಿಸಿ',
      'tenant': 'ಟೆನಂಟ್',
      'rent': 'ಬಾಡಿಗೆ',
      'monthly_rent': 'ಮಾಸಿಕ ಬಾಡಿಗೆ',
      'phone': 'ಫೋನ್',
      'room': 'ಕೊಠಡಿ',
      'bed': 'ಬೆಡ್',
      'available': 'ಲಭ್ಯವಿದೆ',
      'occupied': 'ಆಕ್ರಮಿತ',
      'total': 'ಒಟ್ಟು',
      'name': 'ಹೆಸರು',
      'date': 'ದಿನಾಂಕ',
      'status': 'ಸ್ಥಿತಿ',
      'notes': 'ಟಿಪ್ಪಣಿಗಳು',
      'confirm': 'ದೃಢೀಕರಿಸಿ',
      'delete': 'ಅಳಿಸಿ',
      'edit': 'ಎಡಿಟ್',
      'update': 'ಅಪ್‌ಡೇಟ್',
      'close': 'ಮುಚ್ಚಿ',
      'back': 'ಹಿಂದೆ',
      'refresh': 'ರಿಫ್ರೆಶ್',
      'language': 'ಭಾಷೆ',
      'select_language': 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'welcome': 'ಸ್ವಾಗತ',
      'recent_transactions': 'ಇತ್ತೀಚಿನ ವಹಿವಾಟುಗಳು',
      'financial_summary': 'ಹಣಕಾಸಿನ ಸಾರಾಂಶ',
      'occupancy_overview': 'ಆಕ್ಯುಪೆನ್ಸಿ ವಿವರ',
      'payment_methods': 'ಪಾವತಿ ವಿಧಾನಗಳು',
      'transaction_summary': 'ವಹಿವಾಟಿನ ಸಾರಾಂಶ',
      'check_in_details': 'ಚೆಕ್-ಇನ್ ವಿವರಗಳು',
      'check_out_details': 'ಚೆಕ್-ಔಟ್ ವಿವರಗಳು',
      'recent_check_ins': 'ಇತ್ತೀಚಿನ ಚೆಕ್-ಇನ್‌ಗಳು',
      'recent_check_outs': 'ಇತ್ತೀಚಿನ ಚೆಕ್-ಔಟ್‌ಗಳು',
      'confirm_check_in': 'ಚೆಕ್-ಇನ್ ದೃಢೀಕರಿಸಿ',
      'confirm_check_out': 'ಚೆಕ್-ಔಟ್ ದೃಢೀಕರಿಸಿ',
      'no_data': 'ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ',
      'loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',

      'property_overview': 'ಪ್ರಾಪರ್ಟಿ ವಿವರಗಳು',
      'quick_actions': 'ತ್ವರಿತ ಕ್ರಮಗಳು',
      'total_rooms': 'ಒಟ್ಟು ಕೊಠಡಿಗಳು',
      'all_rooms': 'ಎಲ್ಲಾ ಕೊಠಡಿಗಳು',
      'total_beds': 'ಒಟ್ಟು ಬೆಡ್\u200cಗಳು',
      'all_beds': 'ಎಲ್ಲಾ ಬೆಡ್\u200cಗಳು',
      'vacant': 'ಖಾಲಿ',
      'today_collection': 'ಇಂದಿನ ವಸೂಲಿ',
      'payments': 'ಪಾವತಿಗಳು',
      'pending_rent': 'ಬಾಕಿ ಬಾಡಿಗೆ',
      'active_tenants': 'ಸಕ್ರಿಯ ಟೆನಂಟ್\u200cಗಳು',
      'this_month_income': 'ಈ ತಿಂಗಳ ಆದಾಯ',
      'all_income': 'ಒಟ್ಟು ಆದಾಯ',
      'this_month_expense': 'ಈ ತಿಂಗಳ ಖರ್ಚು',
      'all_expense': 'ಒಟ್ಟು ಖರ್ಚು',
      'add_payment': 'ಪಾವತಿ ಸೇರಿಸಿ',
      'add_expense': 'ಖರ್ಚು ಸೇರಿಸಿ',
      'create_bill': 'ಬಿಲ್ ರಚಿಸಿ',
      'check_in_out': 'ಚೆಕ್-ಇನ್/ಔಟ್',
      'upload_register': 'ರಿಜಿಸ್ಟರ್ ಅಪ್\u200cಲೋಡ್',
      'pg_apartment_structure': 'PG/ಅಪಾರ್ಟ್\u200cಮೆಂಟ್ ರಚನೆ',
      'home': 'ಹೋಮ್',
      'rooms': 'ಕೊಠಡಿಗಳು',
      'rooms_beds': 'ಕೊಠಡಿಗಳು & ಬೆಡ್\u200cಗಳು',
      'billing': 'ಬಿಲ್ಲಿಂಗ್',
      'documents': 'ದಾಖಲೆಗಳು',
      'notifications': 'ಅಧಿಸೂಚನೆಗಳು',
      'logout': 'ಲಾಗ್ ಔಟ್',
      'current_property': 'ಪ್ರಸ್ತುತ ಪ್ರಾಪರ್ಟಿ',
      'no_pg_configured': 'PG ಸೆಟಪ್ ಆಗಿಲ್ಲ',
      'setup_pg_to_get_started': 'ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ PG ಸೆಟಪ್ ಮಾಡಿ',
      'menu': 'ಮೆನು',
      'accounts': 'ಖಾತೆಗಳು',
      'confirm_logout': 'ನೀವು ಖಚಿತವಾಗಿ ಲಾಗ್ ಔಟ್ ಮಾಡಲು ಬಯಸುವಿರಾ?',
    },

    // ==========================================================
    // HINDI
    // ==========================================================

    'Hindi': {
      'dashboard': 'डैशबोर्ड',
      'settings': 'सेटिंग्स',
      'reports': 'रिपोर्ट',
      'tenant_management': 'किरायेदार प्रबंधन',
      'tenants': 'किरायेदार',
      'check_in': 'चेक-इन',
      'check_out': 'चेक-आउट',
      'day_sheet': 'डे शीट',
      'more': 'और',
      'save': 'सेव करें',
      'cancel': 'रद्द करें',
      'search': 'खोजें',
      'active': 'सक्रिय',
      'vacated': 'खाली किए गए',
      'income': 'आय',
      'expense': 'खर्च',
      'add_tenant': 'किरायेदार जोड़ें',
      'tenant': 'किरायेदार',
      'rent': 'किराया',
      'monthly_rent': 'मासिक किराया',
      'phone': 'फोन',
      'room': 'कमरा',
      'bed': 'बेड',
      'available': 'उपलब्ध',
      'occupied': 'भरा हुआ',
      'total': 'कुल',
      'name': 'नाम',
      'date': 'तारीख',
      'status': 'स्थिति',
      'notes': 'नोट्स',
      'confirm': 'पुष्टि करें',
      'delete': 'हटाएं',
      'edit': 'संपादित करें',
      'update': 'अपडेट करें',
      'close': 'बंद करें',
      'back': 'वापस',
      'refresh': 'रिफ्रेश',
      'language': 'भाषा',
      'select_language': 'भाषा चुनें',
      'welcome': 'स्वागत है',
      'recent_transactions': 'हाल की लेनदेन',
      'financial_summary': 'वित्तीय सारांश',
      'occupancy_overview': 'ऑक्यूपेंसी विवरण',
      'payment_methods': 'भुगतान के तरीके',
      'transaction_summary': 'लेनदेन सारांश',
      'check_in_details': 'चेक-इन विवरण',
      'check_out_details': 'चेक-आउट विवरण',
      'recent_check_ins': 'हाल के चेक-इन',
      'recent_check_outs': 'हाल के चेक-आउट',
      'confirm_check_in': 'चेक-इन की पुष्टि करें',
      'confirm_check_out': 'चेक-आउट की पुष्टि करें',
      'no_data': 'कोई डेटा उपलब्ध नहीं है',
      'loading': 'लोड हो रहा है...',

      'property_overview': 'प्रॉपर्टी विवरण',
      'quick_actions': 'त्वरित कार्रवाइयाँ',
      'total_rooms': 'कुल कमरे',
      'all_rooms': 'सभी कमरे',
      'total_beds': 'कुल बेड',
      'all_beds': 'सभी बेड',
      'vacant': 'खाली',
      'today_collection': 'आज का संग्रह',
      'payments': 'भुगतान',
      'pending_rent': 'बकाया किराया',
      'active_tenants': 'सक्रिय किरायेदार',
      'this_month_income': 'इस महीने की आय',
      'all_income': 'कुल आय',
      'this_month_expense': 'इस महीने का खर्च',
      'all_expense': 'कुल खर्च',
      'add_payment': 'भुगतान जोड़ें',
      'add_expense': 'खर्च जोड़ें',
      'create_bill': 'बिल बनाएं',
      'check_in_out': 'चेक-इन/आउट',
      'upload_register': 'रजिस्टर अपलोड करें',
      'pg_apartment_structure': 'PG/अपार्टमेंट संरचना',
      'home': 'होम',
      'rooms': 'कमरे',
      'rooms_beds': 'कमरे और बेड',
      'billing': 'बिलिंग',
      'documents': 'दस्तावेज़',
      'notifications': 'सूचनाएं',
      'logout': 'लॉग आउट',
      'current_property': 'वर्तमान प्रॉपर्टी',
      'no_pg_configured': 'कोई PG सेट नहीं है',
      'setup_pg_to_get_started': 'शुरू करने के लिए अपना PG सेट करें',
      'menu': 'मेनू',
      'accounts': 'खाते',
      'confirm_logout': 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
    },

    // ==========================================================
    // TAMIL
    // ==========================================================

    'Tamil': {
      'dashboard': 'டாஷ்போர்டு',
      'settings': 'அமைப்புகள்',
      'reports': 'அறிக்கைகள்',
      'tenant_management': 'வாடகையாளர் மேலாண்மை',
      'tenants': 'வாடகையாளர்கள்',
      'check_in': 'செக்-இன்',
      'check_out': 'செக்-அவுட்',
      'day_sheet': 'நாள் தாள்',
      'more': 'மேலும்',
      'save': 'சேமிக்கவும்',
      'cancel': 'ரத்து செய்',
      'search': 'தேடுக',
      'active': 'செயலில்',
      'vacated': 'காலி செய்தவர்கள்',
      'income': 'வருமானம்',
      'expense': 'செலவு',
      'add_tenant': 'வாடகையாளரைச் சேர்க்கவும்',
      'tenant': 'வாடகையாளர்',
      'rent': 'வாடகை',
      'monthly_rent': 'மாத வாடகை',
      'phone': 'தொலைபேசி',
      'room': 'அறை',
      'bed': 'படுக்கை',
      'available': 'கிடைக்கிறது',
      'occupied': 'ஆக்கிரமிக்கப்பட்டது',
      'total': 'மொத்தம்',
      'name': 'பெயர்',
      'date': 'தேதி',
      'status': 'நிலை',
      'notes': 'குறிப்புகள்',
      'confirm': 'உறுதிப்படுத்தவும்',
      'delete': 'நீக்கவும்',
      'edit': 'திருத்து',
      'update': 'புதுப்பிக்கவும்',
      'close': 'மூடு',
      'back': 'பின்செல்',
      'refresh': 'புதுப்பி',
      'language': 'மொழி',
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'welcome': 'வரவேற்கிறோம்',
      'recent_transactions': 'சமீபத்திய பரிவர்த்தனைகள்',
      'financial_summary': 'நிதி சுருக்கம்',
      'occupancy_overview': 'ஆக்கிரமிப்பு விவரம்',
      'payment_methods': 'கட்டண முறைகள்',
      'transaction_summary': 'பரிவர்த்தனை சுருக்கம்',
      'check_in_details': 'செக்-இன் விவரங்கள்',
      'check_out_details': 'செக்-அவுட் விவரங்கள்',
      'recent_check_ins': 'சமீபத்திய செக்-இன்கள்',
      'recent_check_outs': 'சமீபத்திய செக்-அவுட்கள்',
      'confirm_check_in': 'செக்-இனை உறுதிப்படுத்தவும்',
      'confirm_check_out': 'செக்-அவுட்டை உறுதிப்படுத்தவும்',
      'no_data': 'தரவு எதுவும் இல்லை',
      'loading': 'ஏற்றப்படுகிறது...',

      'property_overview': 'சொத்து விவரங்கள்',
      'quick_actions': 'விரைவு செயல்கள்',
      'total_rooms': 'மொத்த அறைகள்',
      'all_rooms': 'அனைத்து அறைகள்',
      'total_beds': 'மொத்த படுக்கைகள்',
      'all_beds': 'அனைத்து படுக்கைகள்',
      'vacant': 'காலி',
      'today_collection': 'இன்றைய வசூல்',
      'payments': 'கட்டணங்கள்',
      'pending_rent': 'நிலுவை வாடகை',
      'active_tenants': 'செயலில் உள்ள வாடகையாளர்கள்',
      'this_month_income': 'இந்த மாத வருமானம்',
      'all_income': 'மொத்த வருமானம்',
      'this_month_expense': 'இந்த மாத செலவு',
      'all_expense': 'மொத்த செலவு',
      'add_payment': 'கட்டணம் சேர்க்கவும்',
      'add_expense': 'செலவு சேர்க்கவும்',
      'create_bill': 'பில் உருவாக்கவும்',
      'check_in_out': 'செக்-இன்/அவுட்',
      'upload_register': 'பதிவேட்டை பதிவேற்றவும்',
      'pg_apartment_structure': 'PG/அபார்ட்மென்ட் அமைப்பு',
      'home': 'முகப்பு',
      'rooms': 'அறைகள்',
      'rooms_beds': 'அறைகள் & படுக்கைகள்',
      'billing': 'பில்லிங்',
      'documents': 'ஆவணங்கள்',
      'notifications': 'அறிவிப்புகள்',
      'logout': 'வெளியேறு',
      'current_property': 'தற்போதைய சொத்து',
      'no_pg_configured': 'PG அமைக்கப்படவில்லை',
      'setup_pg_to_get_started': 'தொடங்க உங்கள் PG-ஐ அமைக்கவும்',
      'menu': 'மெனு',
      'accounts': 'கணக்குகள்',
      'confirm_logout': 'நிச்சயமாக வெளியேற விரும்புகிறீர்களா?',
    },

    // ==========================================================
    // MALAYALAM
    // ==========================================================

    'Malayalam': {
      'dashboard': 'ഡാഷ്ബോർഡ്',
      'settings': 'ക്രമീകരണങ്ങൾ',
      'reports': 'റിപ്പോർട്ടുകൾ',
      'tenant_management': 'വാടകക്കാരുടെ മാനേജ്മെന്റ്',
      'tenants': 'വാടകക്കാർ',
      'check_in': 'ചെക്ക്-ഇൻ',
      'check_out': 'ചെക്ക്-ഔട്ട്',
      'day_sheet': 'ഡേ ഷീറ്റ്',
      'more': 'കൂടുതൽ',
      'save': 'സേവ് ചെയ്യുക',
      'cancel': 'റദ്ദാക്കുക',
      'search': 'തിരയുക',
      'active': 'സജീവം',
      'vacated': 'ഒഴിഞ്ഞവർ',
      'income': 'വരുമാനം',
      'expense': 'ചെലവ്',
      'add_tenant': 'വാടകക്കാരനെ ചേർക്കുക',
      'tenant': 'വാടകക്കാരൻ',
      'rent': 'വാടക',
      'monthly_rent': 'പ്രതിമാസ വാടക',
      'phone': 'ഫോൺ',
      'room': 'മുറി',
      'bed': 'കിടക്ക',
      'available': 'ലഭ്യമാണ്',
      'occupied': 'ഉപയോഗത്തിലാണ്',
      'total': 'ആകെ',
      'name': 'പേര്',
      'date': 'തീയതി',
      'status': 'സ്ഥിതി',
      'notes': 'കുറിപ്പുകൾ',
      'confirm': 'സ്ഥിരീകരിക്കുക',
      'delete': 'ഇല്ലാതാക്കുക',
      'edit': 'തിരുത്തുക',
      'update': 'അപ്‌ഡേറ്റ് ചെയ്യുക',
      'close': 'അടയ്ക്കുക',
      'back': 'പിന്നിലേക്ക്',
      'refresh': 'പുതുക്കുക',
      'language': 'ഭാഷ',
      'select_language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
      'welcome': 'സ്വാഗതം',
      'recent_transactions': 'സമീപകാല ഇടപാടുകൾ',
      'financial_summary': 'സാമ്പത്തിക സംഗ്രഹം',
      'occupancy_overview': 'ഒക്യുപൻസി വിശദാംശങ്ങൾ',
      'payment_methods': 'പണമടയ്ക്കൽ രീതികൾ',
      'transaction_summary': 'ഇടപാട് സംഗ്രഹം',
      'check_in_details': 'ചെക്ക്-ഇൻ വിശദാംശങ്ങൾ',
      'check_out_details': 'ചെക്ക്-ഔട്ട് വിശദാംശങ്ങൾ',
      'recent_check_ins': 'സമീപകാല ചെക്ക്-ഇനുകൾ',
      'recent_check_outs': 'സമീപകാല ചെക്ക്-ഔട്ടുകൾ',
      'confirm_check_in': 'ചെക്ക്-ഇൻ സ്ഥിരീകരിക്കുക',
      'confirm_check_out': 'ചെക്ക്-ഔട്ട് സ്ഥിരീകരിക്കുക',
      'no_data': 'ഡാറ്റ ലഭ്യമല്ല',
      'loading': 'ലോഡ് ചെയ്യുന്നു...',

      'property_overview': 'പ്രോപ്പർട്ടി വിശദാംശങ്ങൾ',
      'quick_actions': 'ദ്രുത പ്രവർത്തനങ്ങൾ',
      'total_rooms': 'ആകെ മുറികൾ',
      'all_rooms': 'എല്ലാ മുറികളും',
      'total_beds': 'ആകെ കിടക്കകൾ',
      'all_beds': 'എല്ലാ കിടക്കകളും',
      'vacant': 'ഒഴിഞ്ഞത്',
      'today_collection': 'ഇന്നത്തെ വരുമാനം',
      'payments': 'പേയ്മെന്റുകൾ',
      'pending_rent': 'കുടിശ്ശിക വാടക',
      'active_tenants': 'സജീവ വാടകക്കാർ',
      'this_month_income': 'ഈ മാസത്തെ വരുമാനം',
      'all_income': 'ആകെ വരുമാനം',
      'this_month_expense': 'ഈ മാസത്തെ ചെലവ്',
      'all_expense': 'ആകെ ചെലവ്',
      'add_payment': 'പേയ്മെന്റ് ചേർക്കുക',
      'add_expense': 'ചെലവ് ചേർക്കുക',
      'create_bill': 'ബിൽ സൃഷ്ടിക്കുക',
      'check_in_out': 'ചെക്ക്-ഇൻ/ഔട്ട്',
      'upload_register': 'രജിസ്റ്റർ അപ്\u200cലോഡ് ചെയ്യുക',
      'pg_apartment_structure': 'PG/അപ്പാർട്ട്മെന്റ് ഘടന',
      'home': 'ഹോം',
      'rooms': 'മുറികൾ',
      'rooms_beds': 'മുറികളും കിടക്കകളും',
      'billing': 'ബില്ലിംഗ്',
      'documents': 'രേഖകൾ',
      'notifications': 'അറിയിപ്പുകൾ',
      'logout': 'ലോഗ് ഔട്ട്',
      'current_property': 'നിലവിലെ പ്രോപ്പർട്ടി',
      'no_pg_configured': 'PG സജ്ജീകരിച്ചിട്ടില്ല',
      'setup_pg_to_get_started': 'ആരംഭിക്കാൻ നിങ്ങളുടെ PG സജ്ജീകരിക്കുക',
      'menu': 'മെനു',
      'accounts': 'അക്കൗണ്ടുകൾ',
      'confirm_logout': 'നിങ്ങൾക്ക് ലോഗ് ഔട്ട് ചെയ്യണമെന്ന് ഉറപ്പാണോ?',
    },

    // ==========================================================
    // MARATHI
    // ==========================================================

    'Marathi': {
      'dashboard': 'डॅशबोर्ड',
      'settings': 'सेटिंग्ज',
      'reports': 'अहवाल',
      'tenant_management': 'भाडेकरू व्यवस्थापन',
      'tenants': 'भाडेकरू',
      'check_in': 'चेक-इन',
      'check_out': 'चेक-आउट',
      'day_sheet': 'डे शीट',
      'more': 'अधिक',
      'save': 'जतन करा',
      'cancel': 'रद्द करा',
      'search': 'शोधा',
      'active': 'सक्रिय',
      'vacated': 'रिकामे केलेले',
      'income': 'उत्पन्न',
      'expense': 'खर्च',
      'add_tenant': 'भाडेकरू जोडा',
      'tenant': 'भाडेकरू',
      'rent': 'भाडे',
      'monthly_rent': 'मासिक भाडे',
      'phone': 'फोन',
      'room': 'खोली',
      'bed': 'बेड',
      'available': 'उपलब्ध',
      'occupied': 'व्याप्त',
      'total': 'एकूण',
      'name': 'नाव',
      'date': 'तारीख',
      'status': 'स्थिती',
      'notes': 'नोंदी',
      'confirm': 'पुष्टी करा',
      'delete': 'हटवा',
      'edit': 'संपादित करा',
      'update': 'अपडेट करा',
      'close': 'बंद करा',
      'back': 'मागे',
      'refresh': 'रिफ्रेश',
      'language': 'भाषा',
      'select_language': 'भाषा निवडा',
      'welcome': 'स्वागत आहे',
      'recent_transactions': 'अलीकडील व्यवहार',
      'financial_summary': 'आर्थिक सारांश',
      'occupancy_overview': 'व्याप्तीचा आढावा',
      'payment_methods': 'पेमेंट पद्धती',
      'transaction_summary': 'व्यवहार सारांश',
      'check_in_details': 'चेक-इन तपशील',
      'check_out_details': 'चेक-आउट तपशील',
      'recent_check_ins': 'अलीकडील चेक-इन',
      'recent_check_outs': 'अलीकडील चेक-आउट',
      'confirm_check_in': 'चेक-इन पुष्टी करा',
      'confirm_check_out': 'चेक-आउट पुष्टी करा',
      'no_data': 'डेटा उपलब्ध नाही',
      'loading': 'लोड होत आहे...',

      'property_overview': 'प्रॉपर्टी तपशील',
      'quick_actions': 'त्वरित कृती',
      'total_rooms': 'एकूण खोल्या',
      'all_rooms': 'सर्व खोल्या',
      'total_beds': 'एकूण बेड',
      'all_beds': 'सर्व बेड',
      'vacant': 'रिकामे',
      'today_collection': 'आजचे संकलन',
      'payments': 'पेमेंट्स',
      'pending_rent': 'थकीत भाडे',
      'active_tenants': 'सक्रिय भाडेकरू',
      'this_month_income': 'या महिन्याचे उत्पन्न',
      'all_income': 'एकूण उत्पन्न',
      'this_month_expense': 'या महिन्याचा खर्च',
      'all_expense': 'एकूण खर्च',
      'add_payment': 'पेमेंट जोडा',
      'add_expense': 'खर्च जोडा',
      'create_bill': 'बिल तयार करा',
      'check_in_out': 'चेक-इन/आउट',
      'upload_register': 'रजिस्टर अपलोड करा',
      'pg_apartment_structure': 'PG/अपार्टमेंट रचना',
      'home': 'होम',
      'rooms': 'खोल्या',
      'rooms_beds': 'खोल्या आणि बेड',
      'billing': 'बिलिंग',
      'documents': 'कागदपत्रे',
      'notifications': 'सूचना',
      'logout': 'लॉग आउट',
      'current_property': 'सध्याची प्रॉपर्टी',
      'no_pg_configured': 'PG सेट केलेले नाही',
      'setup_pg_to_get_started': 'सुरुवात करण्यासाठी तुमचे PG सेट करा',
      'menu': 'मेनू',
      'accounts': 'खाती',
      'confirm_logout': 'तुम्हाला लॉग आउट करायचे आहे का?',
    },

    // ==========================================================
    // BENGALI
    // ==========================================================

    'Bengali': {
      'dashboard': 'ড্যাশবোর্ড',
      'settings': 'সেটিংস',
      'reports': 'রিপোর্ট',
      'tenant_management': 'ভাড়াটিয়া ব্যবস্থাপনা',
      'tenants': 'ভাড়াটিয়ারা',
      'check_in': 'চেক-ইন',
      'check_out': 'চেক-আউট',
      'day_sheet': 'ডে শিট',
      'more': 'আরও',
      'save': 'সংরক্ষণ করুন',
      'cancel': 'বাতিল করুন',
      'search': 'অনুসন্ধান করুন',
      'active': 'সক্রিয়',
      'vacated': 'খালি করা হয়েছে',
      'income': 'আয়',
      'expense': 'খরচ',
      'add_tenant': 'ভাড়াটিয়া যোগ করুন',
      'tenant': 'ভাড়াটিয়া',
      'rent': 'ভাড়া',
      'monthly_rent': 'মাসিক ভাড়া',
      'phone': 'ফোন',
      'room': 'ঘর',
      'bed': 'বেড',
      'available': 'উপলব্ধ',
      'occupied': 'দখল করা',
      'total': 'মোট',
      'name': 'নাম',
      'date': 'তারিখ',
      'status': 'অবস্থা',
      'notes': 'নোট',
      'confirm': 'নিশ্চিত করুন',
      'delete': 'মুছে ফেলুন',
      'edit': 'সম্পাদনা',
      'update': 'আপডেট',
      'close': 'বন্ধ করুন',
      'back': 'পিছনে',
      'refresh': 'রিফ্রেশ',
      'language': 'ভাষা',
      'select_language': 'ভাষা নির্বাচন করুন',
      'welcome': 'স্বাগতম',
      'recent_transactions': 'সাম্প্রতিক লেনদেন',
      'financial_summary': 'আর্থিক সারাংশ',
      'occupancy_overview': 'দখল সংক্রান্ত বিবরণ',
      'payment_methods': 'পেমেন্ট পদ্ধতি',
      'transaction_summary': 'লেনদেনের সারাংশ',
      'check_in_details': 'চেক-ইন বিবরণ',
      'check_out_details': 'চেক-আউট বিবরণ',
      'recent_check_ins': 'সাম্প্রতিক চেক-ইন',
      'recent_check_outs': 'সাম্প্রতিক চেক-আউট',
      'confirm_check_in': 'চেক-ইন নিশ্চিত করুন',
      'confirm_check_out': 'চেক-আউট নিশ্চিত করুন',
      'no_data': 'কোনও ডেটা নেই',
      'loading': 'লোড হচ্ছে...',

      'property_overview': 'প্রপার্টির বিবরণ',
      'quick_actions': 'দ্রুত কাজ',
      'total_rooms': 'মোট ঘর',
      'all_rooms': 'সব ঘর',
      'total_beds': 'মোট বেড',
      'all_beds': 'সব বেড',
      'vacant': 'খালি',
      'today_collection': 'আজকের সংগ্রহ',
      'payments': 'পেমেন্ট',
      'pending_rent': 'বকেয়া ভাড়া',
      'active_tenants': 'সক্রিয় ভাড়াটিয়া',
      'this_month_income': 'এই মাসের আয়',
      'all_income': 'মোট আয়',
      'this_month_expense': 'এই মাসের খরচ',
      'all_expense': 'মোট খরচ',
      'add_payment': 'পেমেন্ট যোগ করুন',
      'add_expense': 'খরচ যোগ করুন',
      'create_bill': 'বিল তৈরি করুন',
      'check_in_out': 'চেক-ইন/আউট',
      'upload_register': 'রেজিস্টার আপলোড করুন',
      'pg_apartment_structure': 'PG/অ্যাপার্টমেন্ট কাঠামো',
      'home': 'হোম',
      'rooms': 'ঘর',
      'rooms_beds': 'ঘর ও বেড',
      'billing': 'বিলিং',
      'documents': 'নথি',
      'notifications': 'বিজ্ঞপ্তি',
      'logout': 'লগ আউট',
      'current_property': 'বর্তমান প্রপার্টি',
      'no_pg_configured': 'কোনো PG সেট করা নেই',
      'setup_pg_to_get_started': 'শুরু করতে আপনার PG সেট করুন',
      'menu': 'মেনু',
      'accounts': 'অ্যাকাউন্টস',
      'confirm_logout': 'আপনি কি লগ আউট করতে চান?',
    },

    // ==========================================================
    // GUJARATI
    // ==========================================================

    'Gujarati': {
      'dashboard': 'ડેશબોર્ડ',
      'settings': 'સેટિંગ્સ',
      'reports': 'અહેવાલો',
      'tenant_management': 'ભાડૂત વ્યવસ્થાપન',
      'tenants': 'ભાડૂતો',
      'check_in': 'ચેક-ઇન',
      'check_out': 'ચેક-આઉટ',
      'day_sheet': 'ડે શીટ',
      'more': 'વધુ',
      'save': 'સાચવો',
      'cancel': 'રદ કરો',
      'search': 'શોધો',
      'active': 'સક્રિય',
      'vacated': 'ખાલી કરેલ',
      'income': 'આવક',
      'expense': 'ખર્ચ',
      'add_tenant': 'ભાડૂત ઉમેરો',
      'tenant': 'ભાડૂત',
      'rent': 'ભાડું',
      'monthly_rent': 'માસિક ભાડું',
      'phone': 'ફોન',
      'room': 'રૂમ',
      'bed': 'બેડ',
      'available': 'ઉપલબ્ધ',
      'occupied': 'કબજામાં',
      'total': 'કુલ',
      'name': 'નામ',
      'date': 'તારીખ',
      'status': 'સ્થિતિ',
      'notes': 'નોંધ',
      'confirm': 'પુષ્ટિ કરો',
      'delete': 'કાઢી નાખો',
      'edit': 'ફેરફાર કરો',
      'update': 'અપડેટ કરો',
      'close': 'બંધ કરો',
      'back': 'પાછા',
      'refresh': 'રિફ્રેશ',
      'language': 'ભાષા',
      'select_language': 'ભાષા પસંદ કરો',
      'welcome': 'સ્વાગત છે',
      'recent_transactions': 'તાજેતરના વ્યવહારો',
      'financial_summary': 'નાણાકીય સારાંશ',
      'occupancy_overview': 'ઓક્યુપન્સી વિગતો',
      'payment_methods': 'ચુકવણી પદ્ધતિઓ',
      'transaction_summary': 'વ્યવહાર સારાંશ',
      'check_in_details': 'ચેક-ઇન વિગતો',
      'check_out_details': 'ચેક-આઉટ વિગતો',
      'recent_check_ins': 'તાજેતરના ચેક-ઇન',
      'recent_check_outs': 'તાજેતરના ચેક-આઉટ',
      'confirm_check_in': 'ચેક-ઇનની પુષ્ટિ કરો',
      'confirm_check_out': 'ચેક-આઉટની પુષ્ટિ કરો',
      'no_data': 'ડેટા ઉપલબ્ધ નથી',
      'loading': 'લોડ થઈ રહ્યું છે...',

      'property_overview': 'પ્રોપર્ટીની વિગતો',
      'quick_actions': 'ઝડપી ક્રિયાઓ',
      'total_rooms': 'કુલ રૂમ',
      'all_rooms': 'બધા રૂમ',
      'total_beds': 'કુલ બેડ',
      'all_beds': 'બધા બેડ',
      'vacant': 'ખાલી',
      'today_collection': 'આજની વસૂલાત',
      'payments': 'ચુકવણીઓ',
      'pending_rent': 'બાકી ભાડું',
      'active_tenants': 'સક્રિય ભાડૂતો',
      'this_month_income': 'આ મહિનાની આવક',
      'all_income': 'કુલ આવક',
      'this_month_expense': 'આ મહિનાનો ખર્ચ',
      'all_expense': 'કુલ ખર્ચ',
      'add_payment': 'ચુકવણી ઉમેરો',
      'add_expense': 'ખર્ચ ઉમેરો',
      'create_bill': 'બિલ બનાવો',
      'check_in_out': 'ચેક-ઇન/આઉટ',
      'upload_register': 'રજિસ્ટર અપલોડ કરો',
      'pg_apartment_structure': 'PG/એપાર્ટમેન્ટ માળખું',
      'home': 'હોમ',
      'rooms': 'રૂમ',
      'rooms_beds': 'રૂમ અને બેડ',
      'billing': 'બિલિંગ',
      'documents': 'દસ્તાવેજો',
      'notifications': 'સૂચનાઓ',
      'logout': 'લૉગ આઉટ',
      'current_property': 'વર્તમાન પ્રોપર્ટી',
      'no_pg_configured': 'PG સેટ નથી',
      'setup_pg_to_get_started': 'શરૂ કરવા માટે તમારું PG સેટ કરો',
      'menu': 'મેનુ',
      'accounts': 'એકાઉન્ટ્સ',
      'confirm_logout': 'શું તમે ખરેખર લૉગ આઉટ કરવા માંગો છો?',
    },

    // ==========================================================
    // PUNJABI
    // ==========================================================

    'Punjabi': {
      'dashboard': 'ਡੈਸ਼ਬੋਰਡ',
      'settings': 'ਸੈਟਿੰਗਾਂ',
      'reports': 'ਰਿਪੋਰਟਾਂ',
      'tenant_management': 'ਕਿਰਾਏਦਾਰ ਪ੍ਰਬੰਧਨ',
      'tenants': 'ਕਿਰਾਏਦਾਰ',
      'check_in': 'ਚੈੱਕ-ਇਨ',
      'check_out': 'ਚੈੱਕ-ਆਉਟ',
      'day_sheet': 'ਡੇ ਸ਼ੀਟ',
      'more': 'ਹੋਰ',
      'save': 'ਸੇਵ ਕਰੋ',
      'cancel': 'ਰੱਦ ਕਰੋ',
      'search': 'ਖੋਜੋ',
      'active': 'ਸਰਗਰਮ',
      'vacated': 'ਖਾਲੀ ਕੀਤੇ',
      'income': 'ਆਮਦਨ',
      'expense': 'ਖਰਚਾ',
      'add_tenant': 'ਕਿਰਾਏਦਾਰ ਸ਼ਾਮਲ ਕਰੋ',
      'tenant': 'ਕਿਰਾਏਦਾਰ',
      'rent': 'ਕਿਰਾਇਆ',
      'monthly_rent': 'ਮਹੀਨਾਵਾਰ ਕਿਰਾਇਆ',
      'phone': 'ਫੋਨ',
      'room': 'ਕਮਰਾ',
      'bed': 'ਬੈੱਡ',
      'available': 'ਉਪਲਬਧ',
      'occupied': 'ਭਰਿਆ ਹੋਇਆ',
      'total': 'ਕੁੱਲ',
      'name': 'ਨਾਮ',
      'date': 'ਮਿਤੀ',
      'status': 'ਸਥਿਤੀ',
      'notes': 'ਨੋਟਸ',
      'confirm': 'ਪੁਸ਼ਟੀ ਕਰੋ',
      'delete': 'ਮਿਟਾਓ',
      'edit': 'ਸੋਧੋ',
      'update': 'ਅੱਪਡੇਟ ਕਰੋ',
      'close': 'ਬੰਦ ਕਰੋ',
      'back': 'ਵਾਪਸ',
      'refresh': 'ਰਿਫ੍ਰੈਸ਼',
      'language': 'ਭਾਸ਼ਾ',
      'select_language': 'ਭਾਸ਼ਾ ਚੁਣੋ',
      'welcome': 'ਜੀ ਆਇਆਂ ਨੂੰ',
      'recent_transactions': 'ਹਾਲੀਆ ਲੈਣ-ਦੇਣ',
      'financial_summary': 'ਵਿੱਤੀ ਸਾਰ',
      'occupancy_overview': 'ਕਬਜ਼ੇ ਦੀ ਜਾਣਕਾਰੀ',
      'payment_methods': 'ਭੁਗਤਾਨ ਦੇ ਤਰੀਕੇ',
      'transaction_summary': 'ਲੈਣ-ਦੇਣ ਦਾ ਸਾਰ',
      'check_in_details': 'ਚੈੱਕ-ਇਨ ਵੇਰਵੇ',
      'check_out_details': 'ਚੈੱਕ-ਆਉਟ ਵੇਰਵੇ',
      'recent_check_ins': 'ਹਾਲੀਆ ਚੈੱਕ-ਇਨ',
      'recent_check_outs': 'ਹਾਲੀਆ ਚੈੱਕ-ਆਉਟ',
      'confirm_check_in': 'ਚੈੱਕ-ਇਨ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      'confirm_check_out': 'ਚੈੱਕ-ਆਉਟ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      'no_data': 'ਕੋਈ ਡਾਟਾ ਉਪਲਬਧ ਨਹੀਂ',
      'loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',

      'property_overview': 'ਪ੍ਰਾਪਰਟੀ ਵੇਰਵੇ',
      'quick_actions': 'ਤੁਰੰਤ ਕਾਰਵਾਈਆਂ',
      'total_rooms': 'ਕੁੱਲ ਕਮਰੇ',
      'all_rooms': 'ਸਾਰੇ ਕਮਰੇ',
      'total_beds': 'ਕੁੱਲ ਬੈੱਡ',
      'all_beds': 'ਸਾਰੇ ਬੈੱਡ',
      'vacant': 'ਖਾਲੀ',
      'today_collection': 'ਅੱਜ ਦੀ ਵਸੂਲੀ',
      'payments': 'ਭੁਗਤਾਨ',
      'pending_rent': 'ਬਕਾਇਆ ਕਿਰਾਇਆ',
      'active_tenants': 'ਸਰਗਰਮ ਕਿਰਾਏਦਾਰ',
      'this_month_income': 'ਇਸ ਮਹੀਨੇ ਦੀ ਆਮਦਨ',
      'all_income': 'ਕੁੱਲ ਆਮਦਨ',
      'this_month_expense': 'ਇਸ ਮਹੀਨੇ ਦਾ ਖਰਚਾ',
      'all_expense': 'ਕੁੱਲ ਖਰਚਾ',
      'add_payment': 'ਭੁਗਤਾਨ ਸ਼ਾਮਲ ਕਰੋ',
      'add_expense': 'ਖਰਚਾ ਸ਼ਾਮਲ ਕਰੋ',
      'create_bill': 'ਬਿੱਲ ਬਣਾਓ',
      'check_in_out': 'ਚੈੱਕ-ਇਨ/ਆਉਟ',
      'upload_register': 'ਰਜਿਸਟਰ ਅੱਪਲੋਡ ਕਰੋ',
      'pg_apartment_structure': 'PG/ਅਪਾਰਟਮੈਂਟ ਢਾਂਚਾ',
      'home': 'ਹੋਮ',
      'rooms': 'ਕਮਰੇ',
      'rooms_beds': 'ਕਮਰੇ ਅਤੇ ਬੈੱਡ',
      'billing': 'ਬਿਲਿੰਗ',
      'documents': 'ਦਸਤਾਵੇਜ਼',
      'notifications': 'ਸੂਚਨਾਵਾਂ',
      'logout': 'ਲੌਗ ਆਉਟ',
      'current_property': 'ਮੌਜੂਦਾ ਪ੍ਰਾਪਰਟੀ',
      'no_pg_configured': 'PG ਸੈੱਟ ਨਹੀਂ ਹੈ',
      'setup_pg_to_get_started': 'ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਆਪਣਾ PG ਸੈੱਟ ਕਰੋ',
      'menu': 'ਮੀਨੂ',
      'accounts': 'ਖਾਤੇ',
      'confirm_logout': 'ਕੀ ਤੁਸੀਂ ਯਕੀਨੀ ਤੌਰ ਤੇ ਲੌਗ ਆਉਟ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?',
    },

    // ==========================================================
    // ODIA
    // ==========================================================

    'Odia': {
      'dashboard': 'ଡ୍ୟାସବୋର୍ଡ',
      'settings': 'ସେଟିଂସ୍',
      'reports': 'ରିପୋର୍ଟ',
      'tenant_management': 'ଭଡ଼ାଟିଆ ପରିଚାଳନା',
      'tenants': 'ଭଡ଼ାଟିଆ',
      'check_in': 'ଚେକ୍-ଇନ୍',
      'check_out': 'ଚେକ୍-ଆଉଟ୍',
      'day_sheet': 'ଡେ ଶିଟ୍',
      'more': 'ଅଧିକ',
      'save': 'ସଂରକ୍ଷଣ କରନ୍ତୁ',
      'cancel': 'ବାତିଲ୍ କରନ୍ତୁ',
      'search': 'ଖୋଜନ୍ତୁ',
      'active': 'ସକ୍ରିୟ',
      'vacated': 'ଖାଲି କରିଛନ୍ତି',
      'income': 'ଆୟ',
      'expense': 'ଖର୍ଚ୍ଚ',
      'add_tenant': 'ଭଡ଼ାଟିଆ ଯୋଡନ୍ତୁ',
      'tenant': 'ଭଡ଼ାଟିଆ',
      'rent': 'ଭଡ଼ା',
      'monthly_rent': 'ମାସିକ ଭଡ଼ା',
      'phone': 'ଫୋନ୍',
      'room': 'କୋଠରୀ',
      'bed': 'ବେଡ୍',
      'available': 'ଉପଲବ୍ଧ',
      'occupied': 'ଦଖଲ ହୋଇଛି',
      'total': 'ମୋଟ',
      'name': 'ନାମ',
      'date': 'ତାରିଖ',
      'status': 'ସ୍ଥିତି',
      'notes': 'ଟିପ୍ପଣୀ',
      'confirm': 'ନିଶ୍ଚିତ କରନ୍ତୁ',
      'delete': 'ଡିଲିଟ୍ କରନ୍ତୁ',
      'edit': 'ସଂପାଦନ କରନ୍ତୁ',
      'update': 'ଅପଡେଟ୍ କରନ୍ତୁ',
      'close': 'ବନ୍ଦ କରନ୍ତୁ',
      'back': 'ପଛକୁ',
      'refresh': 'ରିଫ୍ରେସ୍',
      'language': 'ଭାଷା',
      'select_language': 'ଭାଷା ବାଛନ୍ତୁ',
      'welcome': 'ସ୍ୱାଗତ',
      'recent_transactions': 'ସାମ୍ପ୍ରତିକ କାରବାର',
      'financial_summary': 'ଆର୍ଥିକ ସାରାଂଶ',
      'occupancy_overview': 'ଅକ୍ୟୁପାନ୍ସି ବିବରଣୀ',
      'payment_methods': 'ପେମେଣ୍ଟ ପଦ୍ଧତି',
      'transaction_summary': 'କାରବାର ସାରାଂଶ',
      'check_in_details': 'ଚେକ୍-ଇନ୍ ବିବରଣୀ',
      'check_out_details': 'ଚେକ୍-ଆଉଟ୍ ବିବରଣୀ',
      'recent_check_ins': 'ସାମ୍ପ୍ରତିକ ଚେକ୍-ଇନ୍',
      'recent_check_outs': 'ସାମ୍ପ୍ରତିକ ଚେକ୍-ଆଉଟ୍',
      'confirm_check_in': 'ଚେକ୍-ଇନ୍ ନିଶ୍ଚିତ କରନ୍ତୁ',
      'confirm_check_out': 'ଚେକ୍-ଆଉଟ୍ ନିଶ୍ଚିତ କରନ୍ତୁ',
      'no_data': 'କୌଣସି ଡାଟା ନାହିଁ',
      'loading': 'ଲୋଡ୍ ହେଉଛି...',

      'property_overview': 'ପ୍ରପର୍ଟି ବିବରଣୀ',
      'quick_actions': 'ଦ୍ରୁତ କାର୍ଯ୍ୟ',
      'total_rooms': 'ମୋଟ କୋଠରୀ',
      'all_rooms': 'ସମସ୍ତ କୋଠରୀ',
      'total_beds': 'ମୋଟ ବେଡ୍',
      'all_beds': 'ସମସ୍ତ ବେଡ୍',
      'vacant': 'ଖାଲି',
      'today_collection': 'ଆଜିର ସଂଗ୍ରହ',
      'payments': 'ପେମେଣ୍ଟ',
      'pending_rent': 'ବକେୟା ଭଡ଼ା',
      'active_tenants': 'ସକ୍ରିୟ ଭଡ଼ାଟିଆ',
      'this_month_income': 'ଏହି ମାସର ଆୟ',
      'all_income': 'ମୋଟ ଆୟ',
      'this_month_expense': 'ଏହି ମାସର ଖର୍ଚ୍ଚ',
      'all_expense': 'ମୋଟ ଖର୍ଚ୍ଚ',
      'add_payment': 'ପେମେଣ୍ଟ ଯୋଡନ୍ତୁ',
      'add_expense': 'ଖର୍ଚ୍ଚ ଯୋଡନ୍ତୁ',
      'create_bill': 'ବିଲ୍ ତିଆରି କରନ୍ତୁ',
      'check_in_out': 'ଚେକ୍-ଇନ୍/ଆଉଟ୍',
      'upload_register': 'ରେଜିଷ୍ଟର ଅପଲୋଡ୍ କରନ୍ତୁ',
      'pg_apartment_structure': 'PG/ଆପାର୍ଟମେଣ୍ଟ ଗଠନ',
      'home': 'ହୋମ୍',
      'rooms': 'କୋଠରୀ',
      'rooms_beds': 'କୋଠରୀ ଓ ବେଡ୍',
      'billing': 'ବିଲିଂ',
      'documents': 'ଦଲିଲ',
      'notifications': 'ବିଜ୍ଞପ୍ତି',
      'logout': 'ଲଗ୍ ଆଉଟ୍',
      'current_property': 'ବର୍ତ୍ତମାନ ପ୍ରପର୍ଟି',
      'no_pg_configured': 'PG ସେଟ୍ ହୋଇନାହିଁ',
      'setup_pg_to_get_started': 'ଆରମ୍ଭ କରିବାକୁ ଆପଣଙ୍କ PG ସେଟ୍ କରନ୍ତୁ',
      'menu': 'ମେନୁ',
      'accounts': 'ଖାତା',
      'confirm_logout': 'ଆପଣ ନିଶ୍ଚିତ ଭାବେ ଲଗ୍ ଆଉଟ୍ କରିବାକୁ ଚାହୁଁଛନ୍ତି କି?',
    },

    // ==========================================================
    // ASSAMESE
    // ==========================================================

    'Assamese': {
      'dashboard': 'ডেশ্বব’ৰ্ড',
      'settings': 'ছেটিংছ',
      'reports': 'প্ৰতিবেদন',
      'tenant_management': 'ভাড়াতীয়া ব্যৱস্থাপনা',
      'tenants': 'ভাড়াতীয়া',
      'check_in': 'চেক-ইন',
      'check_out': 'চেক-আউট',
      'day_sheet': 'ডে শ্বীট',
      'more': 'অধিক',
      'save': 'সংৰক্ষণ কৰক',
      'cancel': 'বাতিল কৰক',
      'search': 'সন্ধান কৰক',
      'active': 'সক্ৰিয়',
      'vacated': 'খালী কৰা',
      'income': 'আয়',
      'expense': 'খৰচ',
      'add_tenant': 'ভাড়াতীয়া যোগ কৰক',
      'tenant': 'ভাড়াতীয়া',
      'rent': 'ভাড়া',
      'monthly_rent': 'মাহিলী ভাড়া',
      'phone': 'ফোন',
      'room': 'কোঠা',
      'bed': 'বেড',
      'available': 'উপলব্ধ',
      'occupied': 'দখল কৰা',
      'total': 'মুঠ',
      'name': 'নাম',
      'date': 'তাৰিখ',
      'status': 'স্থিতি',
      'notes': 'টোকা',
      'confirm': 'নিশ্চিত কৰক',
      'delete': 'মচি পেলাওক',
      'edit': 'সম্পাদনা কৰক',
      'update': 'আপডেট কৰক',
      'close': 'বন্ধ কৰক',
      'back': 'পিছলৈ',
      'refresh': 'ৰিফ্ৰেছ',
      'language': 'ভাষা',
      'select_language': 'ভাষা বাছনি কৰক',
      'welcome': 'স্বাগতম',
      'recent_transactions': 'শেহতীয়া লেনদেন',
      'financial_summary': 'বিত্তীয় সাৰাংশ',
      'occupancy_overview': 'অকুপেন্সী বিৱৰণ',
      'payment_methods': 'পেমেণ্ট পদ্ধতি',
      'transaction_summary': 'লেনদেনৰ সাৰাংশ',
      'check_in_details': 'চেক-ইন বিৱৰণ',
      'check_out_details': 'চেক-আউট বিৱৰণ',
      'recent_check_ins': 'শেহতীয়া চেক-ইন',
      'recent_check_outs': 'শেহতীয়া চেক-আউট',
      'confirm_check_in': 'চেক-ইন নিশ্চিত কৰক',
      'confirm_check_out': 'চেক-আউট নিশ্চিত কৰক',
      'no_data': 'কোনো তথ্য উপলব্ধ নহয়',
      'loading': 'লোড হৈ আছে...',

      'property_overview': 'সম্পত্তিৰ বিৱৰণ',
      'quick_actions': 'দ্ৰুত কাৰ্য',
      'total_rooms': 'মুঠ কোঠা',
      'all_rooms': 'সকলো কোঠা',
      'total_beds': 'মুঠ বেড',
      'all_beds': 'সকলো বেড',
      'vacant': 'খালী',
      'today_collection': 'আজিৰ সংগ্ৰহ',
      'payments': 'পেমেণ্ট',
      'pending_rent': 'বাকী ভাড়া',
      'active_tenants': 'সক্ৰিয় ভাড়াতীয়া',
      'this_month_income': 'এই মাহৰ আয়',
      'all_income': 'মুঠ আয়',
      'this_month_expense': 'এই মাহৰ খৰচ',
      'all_expense': 'মুঠ খৰচ',
      'add_payment': 'পেমেণ্ট যোগ কৰক',
      'add_expense': 'খৰচ যোগ কৰক',
      'create_bill': 'বিল বনাওক',
      'check_in_out': 'চেক-ইন/আউট',
      'upload_register': 'ৰেজিষ্টাৰ আপলোড কৰক',
      'pg_apartment_structure': 'PG/এপাৰ্টমেণ্ট গঠন',
      'home': 'হোম',
      'rooms': 'কোঠা',
      'rooms_beds': 'কোঠা আৰু বেড',
      'billing': 'বিলিং',
      'documents': 'নথি',
      'notifications': 'জাননী',
      'logout': 'লগ আউট',
      'current_property': 'বৰ্তমান সম্পত্তি',
      'no_pg_configured': 'PG ছেট কৰা হোৱা নাই',
      'setup_pg_to_get_started': 'আৰম্ভ কৰিবলৈ আপোনাৰ PG ছেট কৰক',
      'menu': 'মেনু',
      'accounts': 'একাউণ্ট',
      'confirm_logout': 'আপুনি নিশ্চিতভাৱে লগ আউট কৰিব বিচাৰে নেকি?',
    },

    // ==========================================================
    // URDU
    // ==========================================================

    'Urdu': {
      'dashboard': 'ڈیش بورڈ',
      'settings': 'ترتیبات',
      'reports': 'رپورٹس',
      'tenant_management': 'کرایہ داروں کا انتظام',
      'tenants': 'کرایہ دار',
      'check_in': 'چیک اِن',
      'check_out': 'چیک آؤٹ',
      'day_sheet': 'ڈے شیٹ',
      'more': 'مزید',
      'save': 'محفوظ کریں',
      'cancel': 'منسوخ کریں',
      'search': 'تلاش کریں',
      'active': 'فعال',
      'vacated': 'خالی کیا گیا',
      'income': 'آمدنی',
      'expense': 'خرچ',
      'add_tenant': 'کرایہ دار شامل کریں',
      'tenant': 'کرایہ دار',
      'rent': 'کرایہ',
      'monthly_rent': 'ماہانہ کرایہ',
      'phone': 'فون',
      'room': 'کمرہ',
      'bed': 'بستر',
      'available': 'دستیاب',
      'occupied': 'مصروف',
      'total': 'کل',
      'name': 'نام',
      'date': 'تاریخ',
      'status': 'حالت',
      'notes': 'نوٹس',
      'confirm': 'تصدیق کریں',
      'delete': 'حذف کریں',
      'edit': 'ترمیم کریں',
      'update': 'اپ ڈیٹ کریں',
      'close': 'بند کریں',
      'back': 'واپس',
      'refresh': 'ریفریش',
      'language': 'زبان',
      'select_language': 'زبان منتخب کریں',
      'welcome': 'خوش آمدید',
      'recent_transactions': 'حالیہ لین دین',
      'financial_summary': 'مالی خلاصہ',
      'occupancy_overview': 'قبضے کی تفصیلات',
      'payment_methods': 'ادائیگی کے طریقے',
      'transaction_summary': 'لین دین کا خلاصہ',
      'check_in_details': 'چیک اِن کی تفصیلات',
      'check_out_details': 'چیک آؤٹ کی تفصیلات',
      'recent_check_ins': 'حالیہ چیک اِن',
      'recent_check_outs': 'حالیہ چیک آؤٹ',
      'confirm_check_in': 'چیک اِن کی تصدیق کریں',
      'confirm_check_out': 'چیک آؤٹ کی تصدیق کریں',
      'no_data': 'کوئی ڈیٹا دستیاب نہیں',
      'loading': 'لوڈ ہو رہا ہے...',

      'property_overview': 'پراپرٹی کی تفصیلات',
      'quick_actions': 'فوری اقدامات',
      'total_rooms': 'کل کمرے',
      'all_rooms': 'تمام کمرے',
      'total_beds': 'کل بیڈ',
      'all_beds': 'تمام بیڈ',
      'vacant': 'خالی',
      'today_collection': 'آج کی وصولی',
      'payments': 'ادائیگیاں',
      'pending_rent': 'بقایا کرایہ',
      'active_tenants': 'فعال کرایہ دار',
      'this_month_income': 'اس ماہ کی آمدنی',
      'all_income': 'کل آمدنی',
      'this_month_expense': 'اس ماہ کا خرچ',
      'all_expense': 'کل خرچ',
      'add_payment': 'ادائیگی شامل کریں',
      'add_expense': 'خرچ شامل کریں',
      'create_bill': 'بل بنائیں',
      'check_in_out': 'چیک اِن/آؤٹ',
      'upload_register': 'رجسٹر اپ لوڈ کریں',
      'pg_apartment_structure': 'PG/اپارٹمنٹ ڈھانچہ',
      'home': 'ہوم',
      'rooms': 'کمرے',
      'rooms_beds': 'کمرے اور بیڈ',
      'billing': 'بلنگ',
      'documents': 'دستاویزات',
      'notifications': 'اطلاعات',
      'logout': 'لاگ آؤٹ',
      'current_property': 'موجودہ پراپرٹی',
      'no_pg_configured': 'کوئی PG سیٹ نہیں ہے',
      'setup_pg_to_get_started': 'شروع کرنے کے لیے اپنا PG سیٹ کریں',
      'menu': 'مینو',
      'accounts': 'اکاؤنٹس',
      'confirm_logout': 'کیا آپ واقعی لاگ آؤٹ کرنا چاہتے ہیں؟',
    },
  };
}